// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              int32
	FirstName       string
	LastName        string
	Email           string
	IsEmailVerified bool
	Password        string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}
